-- Idempotent create table for training_course_records
-- Safe to paste into Supabase SQL editor and run.
CREATE TABLE IF NOT EXISTS public.training_course_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NULL,
  course_name text NOT NULL,
  course_date date NOT NULL,
  description text NULL,
  attachment_url text NULL,
  admin_notes text NULL,
  created_at timestamp without time zone NULL DEFAULT now(),
  submitted_by uuid NULL,
  course_title character varying(200) NULL,
  provider character varying(200) NULL,
  country character varying(100) NULL,
  city character varying(100) NULL,
  start_date date NULL,
  end_date date NULL,
  duration integer NULL,
  objectives text NULL,
  certification character varying(200) NULL,
  skills text NULL,
  course_fees numeric(12,2) NULL,
  travel_accommodation numeric(12,2) NULL,
  daily_allowance numeric(12,2) NULL,
  nominated_by character varying(100) NULL,
  approval_date date NULL,
  feedback text NULL,
  supervisor_evaluation text NULL,
  attachments text NULL,
  city_place_id text NULL,
  total_cost numeric(12,2) NULL,
  CONSTRAINT training_course_records_pkey PRIMARY KEY (id),
  CONSTRAINT training_course_records_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees (id)
) TABLESPACE pg_default;
