-- Create table to persist skipped payroll records
create table if not exists public.payroll_run_skips (
  id bigint generated by default as identity primary key,
  employee_id uuid not null references public.employees (id) on delete cascade,
  payroll_date date not null,
  reason text not null,
  created_at timestamp with time zone not null default now()
);

create index if not exists idx_payroll_run_skips_emp_date
  on public.payroll_run_skips (employee_id, payroll_date);
